jms:
messagingIbmQueueName:
appName: shine_demo
messagingIbmSslProtocol: TLS
messagingIbmKeyStoreType: JKS
messagingIbmKeyStoreLocation:
messagingIbmKeyStoreCode:
messagingIbmHostName:
messagingIbmQueueManager:
messagingIbmPort:
messagingIbmChannel:
messagingIbmCipherSuite: